import { DocumentTemplate, TemplateField, GeneratedDocument } from '../types/document';
import { PAGE_WIDTH, PAGE_HEIGHT, generateMasterResponsabilidadePdf } from './pdfGenerator';

const TEMPLATES_STORAGE_KEY = 'preenchendo_ai_templates_v1';
const HISTORY_STORAGE_KEY = 'preenchendo_ai_history_v1';

export const INITIAL_RESPONSABILIDADE_FIELDS: TemplateField[] = [
  // --- DECLARANTE ---
  {
    id: 'f_declarante_nome',
    template_id: 'template_termo_responsabilidade',
    field_key: 'declarante_nome',
    label: 'Nome do Declarante',
    description: 'Nome completo do declarante que transfere a responsabilidade',
    page: 1,
    x: 60,
    y: 84,
    width: 288,
    height: 13,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 1,
    group: 'declarante',
    test_value: 'João da Silva',
  },
  {
    id: 'f_declarante_cpf',
    template_id: 'template_termo_responsabilidade',
    field_key: 'declarante_cpf',
    label: 'CPF do Declarante',
    description: 'CPF válido com 11 dígitos',
    page: 1,
    x: 448,
    y: 84,
    width: 105,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'cpf',
    required: true,
    mask: '000.000.000-00',
    auto_resize: true,
    sort_order: 2,
    group: 'declarante',
    test_value: '123.456.789-00',
  },
  {
    id: 'f_declarante_rg',
    template_id: 'template_termo_responsabilidade',
    field_key: 'declarante_rg',
    label: 'RG do Declarante',
    description: 'Registro Geral de identificação',
    page: 1,
    x: 117,
    y: 102,
    width: 110,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'rg',
    required: false,
    auto_resize: true,
    sort_order: 3,
    group: 'declarante',
    test_value: '12.345.678',
  },
  {
    id: 'f_declarante_cnh',
    template_id: 'template_termo_responsabilidade',
    field_key: 'declarante_cnh',
    label: 'CNH do Declarante',
    description: 'Número da Carteira Nacional de Habilitação',
    page: 1,
    x: 274,
    y: 102,
    width: 104,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'cnh',
    required: false,
    auto_resize: true,
    sort_order: 4,
    group: 'declarante',
    test_value: '123456789',
  },
  {
    id: 'f_declarante_endereco',
    template_id: 'template_termo_responsabilidade',
    field_key: 'declarante_endereco',
    label: 'Endereço (Rua, Av, Nº)',
    description: 'Logradouro completo com número e complemento',
    page: 1,
    x: 76,
    y: 120,
    width: 262,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 5,
    group: 'declarante',
    test_value: 'Rua das Flores, 100',
  },
  {
    id: 'f_declarante_cep',
    template_id: 'template_termo_responsabilidade',
    field_key: 'declarante_cep',
    label: 'CEP do Declarante',
    description: 'Código de Endereçamento Postal',
    page: 1,
    x: 377,
    y: 120,
    width: 66,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'cep',
    required: false,
    mask: '00000-000',
    auto_resize: true,
    sort_order: 6,
    group: 'declarante',
    test_value: '13000-000',
  },
  {
    id: 'f_declarante_bairro',
    template_id: 'template_termo_responsabilidade',
    field_key: 'declarante_bairro',
    label: 'Bairro',
    page: 1,
    x: 487,
    y: 120,
    width: 66,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: false,
    auto_resize: true,
    sort_order: 7,
    group: 'declarante',
    test_value: 'Cambuí',
  },
  {
    id: 'f_declarante_municipio',
    template_id: 'template_termo_responsabilidade',
    field_key: 'declarante_municipio',
    label: 'Município / Cidade',
    page: 1,
    x: 87,
    y: 138,
    width: 140,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 8,
    group: 'declarante',
    test_value: 'Campinas',
  },
  {
    id: 'f_declarante_estado',
    template_id: 'template_termo_responsabilidade',
    field_key: 'declarante_estado',
    label: 'UF / Estado',
    page: 1,
    x: 252,
    y: 138,
    width: 22,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'center',
    field_type: 'text',
    max_length: 2,
    required: true,
    auto_resize: true,
    sort_order: 9,
    group: 'declarante',
    test_value: 'SP',
  },
  {
    id: 'f_declarante_telefone',
    template_id: 'template_termo_responsabilidade',
    field_key: 'declarante_telefone',
    label: 'Telefone do Declarante',
    page: 1,
    x: 307,
    y: 138,
    width: 100,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'phone',
    required: false,
    mask: '(00) 00000-0000',
    auto_resize: true,
    sort_order: 10,
    group: 'declarante',
    test_value: '(19) 99876-5432',
  },

  // --- COMPRADOR ---
  {
    id: 'f_comprador_nome',
    template_id: 'template_termo_responsabilidade',
    field_key: 'comprador_nome',
    label: 'Nome do Comprador / Razão Social',
    description: 'Empresa adquirente ou pessoa compradora',
    page: 1,
    x: 137,
    y: 156,
    width: 245,
    height: 13,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 11,
    group: 'comprador',
    test_value: 'Auto Peças & Veículos Campinas Ltda',
  },
  {
    id: 'f_comprador_cnpj',
    template_id: 'template_termo_responsabilidade',
    field_key: 'comprador_cnpj',
    label: 'CNPJ do Comprador',
    description: 'CNPJ da empresa compradora',
    page: 1,
    x: 422,
    y: 156,
    width: 130,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'cnpj',
    required: false,
    mask: '00.000.000/0000-00',
    auto_resize: true,
    sort_order: 12,
    group: 'comprador',
    test_value: '12.345.678/0001-90',
  },

  // --- VEÍCULO ---
  {
    id: 'f_veiculo_marca',
    template_id: 'template_termo_responsabilidade',
    field_key: 'veiculo_marca',
    label: 'Marca do Veículo',
    page: 1,
    x: 82,
    y: 223,
    width: 120,
    height: 13,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 13,
    group: 'veiculo',
    test_value: 'GWM',
  },
  {
    id: 'f_veiculo_modelo',
    template_id: 'template_termo_responsabilidade',
    field_key: 'veiculo_modelo',
    label: 'Modelo do Veículo',
    page: 1,
    x: 252,
    y: 223,
    width: 155,
    height: 13,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 14,
    group: 'veiculo',
    test_value: 'ORA 5 Skin',
  },
  {
    id: 'f_veiculo_modelo_ano',
    template_id: 'template_termo_responsabilidade',
    field_key: 'veiculo_modelo_ano',
    label: 'Ano / Modelo',
    description: 'Ex: 2026/2026',
    page: 1,
    x: 467,
    y: 223,
    width: 76,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: false,
    auto_resize: true,
    sort_order: 15,
    group: 'veiculo',
    test_value: '2026/2026',
  },
  {
    id: 'f_veiculo_cor',
    template_id: 'template_termo_responsabilidade',
    field_key: 'veiculo_cor',
    label: 'Cor do Veículo',
    page: 1,
    x: 72,
    y: 243,
    width: 96,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: false,
    auto_resize: true,
    sort_order: 16,
    group: 'veiculo',
    test_value: 'Branco',
  },
  {
    id: 'f_veiculo_placa',
    template_id: 'template_termo_responsabilidade',
    field_key: 'veiculo_placa',
    label: 'Placa do Veículo',
    description: 'Padrão Mercosul (ABC1D23) ou Antiga (ABC1234)',
    page: 1,
    x: 212,
    y: 243,
    width: 96,
    height: 13,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'plate',
    required: true,
    mask: 'plate',
    auto_resize: true,
    sort_order: 17,
    group: 'veiculo',
    test_value: 'ABC1D23',
  },
  {
    id: 'f_veiculo_chassi',
    template_id: 'template_termo_responsabilidade',
    field_key: 'veiculo_chassi',
    label: 'Chassi do Veículo (VIN)',
    description: '17 caracteres alfanuméricos',
    page: 1,
    x: 357,
    y: 243,
    width: 186,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'chassis',
    required: true,
    mask: 'chassis',
    auto_resize: true,
    sort_order: 18,
    group: 'veiculo',
    test_value: '9BWTESTE123456789',
  },

  // --- PROPRIETÁRIO ---
  {
    id: 'f_proprietario_nome',
    template_id: 'template_termo_responsabilidade',
    field_key: 'proprietario_nome',
    label: 'Nome do Proprietário Anterior',
    page: 1,
    x: 142,
    y: 263,
    width: 400,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: false,
    auto_resize: true,
    sort_order: 19,
    group: 'proprietario',
    test_value: 'João da Silva',
  },
  {
    id: 'f_proprietario_rg',
    template_id: 'template_termo_responsabilidade',
    field_key: 'proprietario_rg',
    label: 'RG do Proprietário',
    page: 1,
    x: 70,
    y: 281,
    width: 108,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'rg',
    required: false,
    auto_resize: true,
    sort_order: 20,
    group: 'proprietario',
    test_value: '12.345.678',
  },
  {
    id: 'f_proprietario_rg_uf',
    template_id: 'template_termo_responsabilidade',
    field_key: 'proprietario_rg_uf',
    label: 'UF do RG',
    page: 1,
    x: 210,
    y: 281,
    width: 24,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'center',
    field_type: 'text',
    max_length: 2,
    required: false,
    auto_resize: true,
    sort_order: 21,
    group: 'proprietario',
    test_value: 'SP',
  },
  {
    id: 'f_proprietario_cpf',
    template_id: 'template_termo_responsabilidade',
    field_key: 'proprietario_cpf',
    label: 'CPF do Proprietário',
    page: 1,
    x: 272,
    y: 281,
    width: 146,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'cpf',
    required: false,
    mask: '000.000.000-00',
    auto_resize: true,
    sort_order: 22,
    group: 'proprietario',
    test_value: '123.456.789-00',
  },

  // --- COMUNICAÇÕES E COBRANÇAS ---
  {
    id: 'f_endereco_residencial',
    template_id: 'template_termo_responsabilidade',
    field_key: 'endereco_residencial',
    label: 'Endereço Residencial para Notificações',
    page: 1,
    x: 147,
    y: 349,
    width: 395,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: false,
    auto_resize: true,
    sort_order: 23,
    group: 'comunicacoes',
    test_value: 'Rua das Flores, 100 - Cambuí - Campinas/SP',
  },
  {
    id: 'f_endereco_comercial',
    template_id: 'template_termo_responsabilidade',
    field_key: 'endereco_comercial',
    label: 'Endereço Comercial',
    page: 1,
    x: 147,
    y: 369,
    width: 395,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: false,
    auto_resize: true,
    sort_order: 24,
    group: 'comunicacoes',
    test_value: 'Av. Brasil, 500 - Sala 12 - Centro',
  },
  {
    id: 'f_telefone_comunicacao',
    template_id: 'template_termo_responsabilidade',
    field_key: 'telefone_comunicacao',
    label: 'Telefone para Contato',
    page: 1,
    x: 92,
    y: 389,
    width: 106,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'phone',
    required: false,
    mask: '(00) 00000-0000',
    auto_resize: true,
    sort_order: 25,
    group: 'comunicacoes',
    test_value: '(19) 3234-5678',
  },
  {
    id: 'f_whatsapp',
    template_id: 'template_termo_responsabilidade',
    field_key: 'whatsapp',
    label: 'WhatsApp',
    page: 1,
    x: 262,
    y: 389,
    width: 106,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'whatsapp',
    required: false,
    mask: '(00) 00000-0000',
    auto_resize: true,
    sort_order: 26,
    group: 'comunicacoes',
    test_value: '(19) 99876-5432',
  },
  {
    id: 'f_email',
    template_id: 'template_termo_responsabilidade',
    field_key: 'email',
    label: 'E-mail de Contato',
    page: 1,
    x: 417,
    y: 389,
    width: 126,
    height: 13,
    font_size: 8,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'email',
    required: false,
    auto_resize: true,
    sort_order: 27,
    group: 'comunicacoes',
    test_value: 'joao.silva@email.com',
  },
  {
    id: 'f_principal_condutor',
    template_id: 'template_termo_responsabilidade',
    field_key: 'principal_condutor',
    label: 'Principal Condutor',
    page: 1,
    x: 137,
    y: 409,
    width: 405,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: false,
    auto_resize: true,
    sort_order: 28,
    group: 'comunicacoes',
    test_value: 'João da Silva',
  },
  {
    id: 'f_cnh_principal_condutor',
    template_id: 'template_termo_responsabilidade',
    field_key: 'cnh_principal_condutor',
    label: 'CNH do Condutor',
    page: 1,
    x: 117,
    y: 429,
    width: 150,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'cnh',
    required: false,
    auto_resize: true,
    sort_order: 29,
    group: 'comunicacoes',
    test_value: '123456789',
  },
  {
    id: 'f_cpf_principal_condutor',
    template_id: 'template_termo_responsabilidade',
    field_key: 'cpf_principal_condutor',
    label: 'CPF do Condutor',
    page: 1,
    x: 352,
    y: 429,
    width: 190,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'cpf',
    required: false,
    mask: '000.000.000-00',
    auto_resize: true,
    sort_order: 30,
    group: 'comunicacoes',
    test_value: '123.456.789-00',
  },

  // --- DATA ---
  {
    id: 'f_data_dia',
    template_id: 'template_termo_responsabilidade',
    field_key: 'data_dia',
    label: 'Dia do Documento',
    page: 1,
    x: 207,
    y: 512,
    width: 26,
    height: 13,
    font_size: 9,
    font_weight: 'normal',
    alignment: 'center',
    field_type: 'text',
    required: true,
    auto_resize: false,
    sort_order: 31,
    group: 'data',
    default_value: String(new Date().getDate()).padStart(2, '0'),
    test_value: '19',
  },
  {
    id: 'f_data_mes',
    template_id: 'template_termo_responsabilidade',
    field_key: 'data_mes',
    label: 'Mês do Documento',
    page: 1,
    x: 257,
    y: 512,
    width: 116,
    height: 13,
    font_size: 9,
    font_weight: 'normal',
    alignment: 'center',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 32,
    group: 'data',
    default_value: [
      'Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho',
      'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'
    ][new Date().getMonth()],
    test_value: 'Agosto',
  },
  {
    id: 'f_data_ano',
    template_id: 'template_termo_responsabilidade',
    field_key: 'data_ano',
    label: 'Ano do Documento (2 dígitos)',
    page: 1,
    x: 405,
    y: 512,
    width: 24,
    height: 13,
    font_size: 9,
    font_weight: 'normal',
    alignment: 'center',
    field_type: 'text',
    required: true,
    auto_resize: false,
    sort_order: 33,
    group: 'data',
    default_value: String(new Date().getFullYear()).slice(-2),
    test_value: '26',
  },
];

export const BUILT_IN_TEMPLATE_RESPONSABILIDADE: DocumentTemplate = {
  id: 'template_termo_responsabilidade',
  name: 'Termo de Responsabilidade',
  description: 'Termo de responsabilidade para transferência de posse e custódia de veículo com dados de comprador, condutor e proprietário.',
  file_hash: 'hash_termo_responsabilidade_v1',
  version: 'v1.0',
  page_count: 1,
  page_width: PAGE_WIDTH,
  page_height: PAGE_HEIGHT,
  status: 'active',
  fields: INITIAL_RESPONSABILIDADE_FIELDS,
  created_at: '2026-01-01T00:00:00.000Z',
  updated_at: '2026-08-19T00:00:00.000Z',
  is_built_in: true,
};

// --- Storage Utilities ---
export function loadAllTemplates(): DocumentTemplate[] {
  try {
    const raw = localStorage.getItem(TEMPLATES_STORAGE_KEY);
    if (!raw) {
      return [BUILT_IN_TEMPLATE_RESPONSABILIDADE];
    }
    const parsed: DocumentTemplate[] = JSON.parse(raw);
    // Ensure built-in template always exists
    const hasBuiltIn = parsed.some((t) => t.id === BUILT_IN_TEMPLATE_RESPONSABILIDADE.id);
    if (!hasBuiltIn) {
      parsed.unshift(BUILT_IN_TEMPLATE_RESPONSABILIDADE);
    }
    return parsed;
  } catch {
    return [BUILT_IN_TEMPLATE_RESPONSABILIDADE];
  }
}

export function saveTemplate(template: DocumentTemplate): void {
  const all = loadAllTemplates();
  const index = all.findIndex((t) => t.id === template.id);
  if (index >= 0) {
    all[index] = { ...template, updated_at: new Date().toISOString() };
  } else {
    all.push({
      ...template,
      created_at: template.created_at || new Date().toISOString(),
      updated_at: new Date().toISOString(),
    });
  }
  localStorage.setItem(TEMPLATES_STORAGE_KEY, JSON.stringify(all));
}

export function deleteTemplate(templateId: string): void {
  const all = loadAllTemplates().filter((t) => t.id !== templateId && !t.is_built_in);
  localStorage.setItem(TEMPLATES_STORAGE_KEY, JSON.stringify(all));
}

export function loadDocumentHistory(): GeneratedDocument[] {
  try {
    const raw = localStorage.getItem(HISTORY_STORAGE_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
}

export function saveDocumentToHistory(doc: GeneratedDocument): void {
  const history = loadDocumentHistory();
  history.unshift(doc);
  // Keep last 50 documents
  if (history.length > 50) history.pop();
  localStorage.setItem(HISTORY_STORAGE_KEY, JSON.stringify(history));
}

export function deleteDocumentFromHistory(docId: string): void {
  const history = loadDocumentHistory().filter((d) => d.id !== docId);
  localStorage.setItem(HISTORY_STORAGE_KEY, JSON.stringify(history));
}

// Master PDF buffer in-memory cache
let cachedMasterPdfBytes: Uint8Array | null = null;

export async function getMasterPdfBytes(template: DocumentTemplate): Promise<Uint8Array> {
  if (template.id === 'template_termo_responsabilidade') {
    if (!cachedMasterPdfBytes) {
      cachedMasterPdfBytes = await generateMasterResponsabilidadePdf();
    }
    return cachedMasterPdfBytes;
  }

  // If custom uploaded template has file_url/base64 in localStorage
  if (template.file_url && template.file_url.startsWith('data:application/pdf;base64,')) {
    const base64Data = template.file_url.split(',')[1];
    const binaryString = atob(base64Data);
    const len = binaryString.length;
    const bytes = new Uint8Array(len);
    for (let i = 0; i < len; i++) {
      bytes[i] = binaryString.charCodeAt(i);
    }
    return bytes;
  }

  // Fallback to built-in
  if (!cachedMasterPdfBytes) {
    cachedMasterPdfBytes = await generateMasterResponsabilidadePdf();
  }
  return cachedMasterPdfBytes;
}
