import { DocumentTemplate, TemplateField, GeneratedDocument } from '../types/document';
import {
  PAGE_WIDTH,
  PAGE_HEIGHT,
  generateMasterResponsabilidadePdf,
  generateMasterCartaCancelamentoPdf,
  generateMasterDacaoPagamentoPdf,
  generateMasterIsencaoNfPdf,
  generateMasterTermoCompraUsadoGwmPdf,
  generateMasterFormularioDevolucaoPdf,
} from './pdfGenerator';

const TEMPLATES_STORAGE_KEY = 'preenchendo_ai_templates_v7';
const HISTORY_STORAGE_KEY = 'preenchendo_ai_history_v7';

export const CURRENT_TEMPLATE_VERSION = 'v7.0_exact_official_dealership_templates_fidelity_dacao_exact';

// 1. TERMO DE RESPONSABILIDADE
export const FIELDS_TERMO_RESPONSABILIDADE: TemplateField[] = [
  {
    id: 'f_declarante_nome',
    template_id: 'template_termo_responsabilidade',
    field_key: 'declarante_nome',
    label: 'Nome do Declarante',
    description: 'Nome completo do declarante que transfere a responsabilidade',
    page: 1,
    x: 96,
    y: 138,
    width: 318,
    height: 13,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 1,
    group: 'declarante',
    test_value: 'João da Silva',
  },
  {
    id: 'f_declarante_cpf',
    template_id: 'template_termo_responsabilidade',
    field_key: 'declarante_cpf',
    label: 'CPF do Declarante',
    description: 'CPF válido com 11 dígitos',
    page: 1,
    x: 98,
    y: 152.5,
    width: 109,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'cpf',
    required: true,
    mask: '000.000.000-00',
    auto_resize: true,
    sort_order: 2,
    group: 'declarante',
    test_value: '123.456.789-00',
  },
  {
    id: 'f_declarante_rg',
    template_id: 'template_termo_responsabilidade',
    field_key: 'declarante_rg',
    label: 'RG do Declarante',
    description: 'Registro Geral de identificação',
    page: 1,
    x: 248,
    y: 152.5,
    width: 97,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'rg',
    required: false,
    auto_resize: true,
    sort_order: 3,
    group: 'declarante',
    test_value: '12.345.678',
  },
  {
    id: 'f_declarante_cnh',
    template_id: 'template_termo_responsabilidade',
    field_key: 'declarante_cnh',
    label: 'CNH do Declarante',
    description: 'Número da Carteira Nacional de Habilitação',
    page: 1,
    x: 402,
    y: 152.5,
    width: 73,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'cnh',
    required: false,
    auto_resize: true,
    sort_order: 4,
    group: 'declarante',
    test_value: '123456789',
  },
  {
    id: 'f_declarante_endereco',
    template_id: 'template_termo_responsabilidade',
    field_key: 'declarante_endereco',
    label: 'Endereço (Rua, Av, Nº)',
    description: 'Logradouro completo com número e complemento',
    page: 1,
    x: 140,
    y: 167,
    width: 370,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 5,
    group: 'declarante',
    test_value: 'Rua das Flores, 100 - Apto 42',
  },
  {
    id: 'f_declarante_cep',
    template_id: 'template_termo_responsabilidade',
    field_key: 'declarante_cep',
    label: 'CEP do Declarante',
    description: 'Código de Endereçamento Postal',
    page: 1,
    x: 102,
    y: 181.5,
    width: 73,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'cep',
    required: true,
    mask: '00000-000',
    auto_resize: true,
    sort_order: 6,
    group: 'declarante',
    test_value: '13000-000',
  },
  {
    id: 'f_declarante_bairro',
    template_id: 'template_termo_responsabilidade',
    field_key: 'declarante_bairro',
    label: 'Bairro',
    page: 1,
    x: 210,
    y: 181.5,
    width: 115,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 7,
    group: 'declarante',
    test_value: 'Cambuí',
  },
  {
    id: 'f_declarante_municipio',
    template_id: 'template_termo_responsabilidade',
    field_key: 'declarante_municipio',
    label: 'Município / Cidade',
    page: 1,
    x: 385,
    y: 181.5,
    width: 80,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 8,
    group: 'declarante',
    test_value: 'Campinas',
  },
  {
    id: 'f_declarante_estado',
    template_id: 'template_termo_responsabilidade',
    field_key: 'declarante_estado',
    label: 'Estado / UF',
    page: 1,
    x: 80,
    y: 196,
    width: 25,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'center',
    field_type: 'state',
    required: true,
    auto_resize: false,
    sort_order: 9,
    group: 'declarante',
    test_value: 'SP',
  },
  {
    id: 'f_declarante_telefone',
    template_id: 'template_termo_responsabilidade',
    field_key: 'declarante_telefone',
    label: 'Telefone do Declarante',
    page: 1,
    x: 175,
    y: 196,
    width: 112,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'phone',
    required: true,
    mask: '(00) 00000-0000',
    auto_resize: true,
    sort_order: 10,
    group: 'declarante',
    test_value: '19 99876-5432',
  },
  {
    id: 'f_comprador_nome',
    template_id: 'template_termo_responsabilidade',
    field_key: 'comprador_nome',
    label: 'Nome do Comprador / Razão Social',
    description: 'Empresa adquirente ou pessoa compradora',
    page: 1,
    x: 308,
    y: 225,
    width: 207,
    height: 13,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 11,
    group: 'comprador',
    test_value: 'Auto Peças & Veículos Campinas Ltda',
  },
  {
    id: 'f_comprador_cnpj',
    template_id: 'template_termo_responsabilidade',
    field_key: 'comprador_cnpj',
    label: 'CNPJ do Comprador',
    description: 'CNPJ da empresa compradora',
    page: 1,
    x: 188,
    y: 239.5,
    width: 132,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'cnpj',
    required: true,
    mask: '00.000.000/0000-00',
    auto_resize: true,
    sort_order: 12,
    group: 'comprador',
    test_value: '12.345.678/0001-90',
  },
  {
    id: 'f_veiculo_marca',
    template_id: 'template_termo_responsabilidade',
    field_key: 'veiculo_marca',
    label: 'Marca do Veículo',
    page: 1,
    x: 108,
    y: 274,
    width: 92,
    height: 13,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 13,
    group: 'veiculo',
    test_value: 'GWM',
  },
  {
    id: 'f_veiculo_modelo',
    template_id: 'template_termo_responsabilidade',
    field_key: 'veiculo_modelo',
    label: 'Modelo do Veículo',
    page: 1,
    x: 240,
    y: 274,
    width: 110,
    height: 13,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 14,
    group: 'veiculo',
    test_value: 'ORA 03 GT',
  },
  {
    id: 'f_veiculo_modelo_ano',
    template_id: 'template_termo_responsabilidade',
    field_key: 'veiculo_modelo_ano',
    label: 'Ano / Modelo',
    description: 'Ex: 2024/2026',
    page: 1,
    x: 406,
    y: 274,
    width: 46,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'year',
    required: true,
    auto_resize: true,
    sort_order: 15,
    group: 'veiculo',
    test_value: '2024/2026',
  },
  {
    id: 'f_veiculo_cor',
    template_id: 'template_termo_responsabilidade',
    field_key: 'veiculo_cor',
    label: 'Cor do Veículo',
    page: 1,
    x: 480,
    y: 274,
    width: 35,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 16,
    group: 'veiculo',
    test_value: 'Cinza',
  },
  {
    id: 'f_veiculo_placa',
    template_id: 'template_termo_responsabilidade',
    field_key: 'veiculo_placa',
    label: 'Placa do Veículo',
    description: 'Padrão Mercosul (ABC1D23) ou Antiga (ABC1234)',
    page: 1,
    x: 106,
    y: 287,
    width: 80,
    height: 13,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'plate',
    required: true,
    auto_resize: true,
    sort_order: 17,
    group: 'veiculo',
    test_value: 'FUE2I35',
  },
  {
    id: 'f_veiculo_chassi',
    template_id: 'template_termo_responsabilidade',
    field_key: 'veiculo_chassi',
    label: 'Chassi do Veículo (VIN)',
    description: '17 caracteres alfanuméricos',
    page: 1,
    x: 224,
    y: 287,
    width: 290,
    height: 13,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'chassis',
    required: true,
    auto_resize: true,
    sort_order: 18,
    group: 'veiculo',
    test_value: 'LGWEEUA56TK606976',
  },
  {
    id: 'f_proprietario_nome',
    template_id: 'template_termo_responsabilidade',
    field_key: 'proprietario_nome',
    label: 'Nome do Proprietário Anterior',
    page: 1,
    x: 135,
    y: 300,
    width: 264,
    height: 13,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 19,
    group: 'proprietario',
    test_value: 'João da Silva',
  },
  {
    id: 'f_proprietario_cpf',
    template_id: 'template_termo_responsabilidade',
    field_key: 'proprietario_cpf',
    label: 'CPF do Proprietário',
    page: 1,
    x: 428,
    y: 300,
    width: 87,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'cpf',
    required: true,
    mask: '000.000.000-00',
    auto_resize: true,
    sort_order: 20,
    group: 'proprietario',
    test_value: '123.456.789-00',
  },
  {
    id: 'f_proprietario_rg',
    template_id: 'template_termo_responsabilidade',
    field_key: 'proprietario_rg',
    label: 'RG do Proprietário',
    page: 1,
    x: 98,
    y: 313,
    width: 132,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'rg',
    required: false,
    auto_resize: true,
    sort_order: 21,
    group: 'proprietario',
    test_value: '12.345.678',
  },
  {
    id: 'f_proprietario_rg_uf',
    template_id: 'template_termo_responsabilidade',
    field_key: 'proprietario_rg_uf',
    label: 'UF do RG',
    page: 1,
    x: 250,
    y: 313,
    width: 30,
    height: 13,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'center',
    field_type: 'state',
    required: false,
    auto_resize: false,
    sort_order: 22,
    group: 'proprietario',
    test_value: 'SP',
  },
  {
    id: 'f_endereco_residencial',
    template_id: 'template_termo_responsabilidade',
    field_key: 'endereco_residencial',
    label: 'Endereço Residencial para Notificações',
    page: 1,
    x: 168,
    y: 668,
    width: 342,
    height: 13,
    font_size: 8,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: false,
    auto_resize: true,
    sort_order: 23,
    group: 'comunicacoes',
    test_value: 'Rua das Flores, 100 - Cambuí - Campinas/SP',
  },
  {
    id: 'f_endereco_comercial',
    template_id: 'template_termo_responsabilidade',
    field_key: 'endereco_comercial',
    label: 'Endereço Comercial',
    page: 1,
    x: 165,
    y: 683,
    width: 345,
    height: 13,
    font_size: 8,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: false,
    auto_resize: true,
    sort_order: 24,
    group: 'comunicacoes',
    test_value: 'Av. Brasil, 500 - Sala 12 - Centro',
  },
  {
    id: 'f_telefone_comunicacao',
    template_id: 'template_termo_responsabilidade',
    field_key: 'telefone_comunicacao',
    label: 'Telefone para Contato',
    page: 1,
    x: 155,
    y: 698,
    width: 160,
    height: 13,
    font_size: 8,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'phone',
    required: false,
    auto_resize: true,
    sort_order: 25,
    group: 'comunicacoes',
    test_value: '(19) 3234-5678',
  },
  {
    id: 'f_whatsapp',
    template_id: 'template_termo_responsabilidade',
    field_key: 'whatsapp',
    label: 'WhatsApp',
    page: 1,
    x: 368,
    y: 698,
    width: 142,
    height: 13,
    font_size: 8,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'phone',
    required: false,
    auto_resize: true,
    sort_order: 26,
    group: 'comunicacoes',
    test_value: '(19) 99876-5432',
  },
  {
    id: 'f_email',
    template_id: 'template_termo_responsabilidade',
    field_key: 'email',
    label: 'E-mail de Contato',
    page: 1,
    x: 115,
    y: 713,
    width: 395,
    height: 13,
    font_size: 8,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'email',
    required: false,
    auto_resize: true,
    sort_order: 27,
    group: 'comunicacoes',
    test_value: 'joao.silva@email.com',
  },
  {
    id: 'f_principal_condutor',
    template_id: 'template_termo_responsabilidade',
    field_key: 'principal_condutor',
    label: 'Principal Condutor',
    page: 1,
    x: 152,
    y: 728,
    width: 358,
    height: 13,
    font_size: 8,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: false,
    auto_resize: true,
    sort_order: 28,
    group: 'comunicacoes',
    test_value: 'João da Silva',
  },
  {
    id: 'f_cnh_principal_condutor',
    template_id: 'template_termo_responsabilidade',
    field_key: 'cnh_principal_condutor',
    label: 'CNH do Condutor',
    page: 1,
    x: 182,
    y: 743,
    width: 160,
    height: 13,
    font_size: 8,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'cnh',
    required: false,
    auto_resize: true,
    sort_order: 29,
    group: 'comunicacoes',
    test_value: '123456789',
  },
  {
    id: 'f_cpf_principal_condutor',
    template_id: 'template_termo_responsabilidade',
    field_key: 'cpf_principal_condutor',
    label: 'CPF do Condutor',
    page: 1,
    x: 368,
    y: 743,
    width: 142,
    height: 13,
    font_size: 8,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'cpf',
    required: false,
    mask: '000.000.000-00',
    auto_resize: true,
    sort_order: 30,
    group: 'comunicacoes',
    test_value: '123.456.789-00',
  },
  {
    id: 'f_data_dia',
    template_id: 'template_termo_responsabilidade',
    field_key: 'data_dia',
    label: 'Dia do Documento',
    page: 1,
    x: 124,
    y: 572,
    width: 26,
    height: 13,
    font_size: 9,
    font_weight: 'normal',
    alignment: 'center',
    field_type: 'number',
    required: true,
    auto_resize: false,
    sort_order: 31,
    group: 'data',
    default_value: String(new Date().getDate()).padStart(2, '0'),
    test_value: '19',
  },
  {
    id: 'f_data_mes',
    template_id: 'template_termo_responsabilidade',
    field_key: 'data_mes',
    label: 'Mês do Documento',
    page: 1,
    x: 166,
    y: 572,
    width: 76,
    height: 13,
    font_size: 9,
    font_weight: 'normal',
    alignment: 'center',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 32,
    group: 'data',
    default_value: [
      'Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho',
      'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'
    ][new Date().getMonth()],
    test_value: 'Agosto',
  },
  {
    id: 'f_data_ano',
    template_id: 'template_termo_responsabilidade',
    field_key: 'data_ano',
    label: 'Ano do Documento',
    page: 1,
    x: 266,
    y: 572,
    width: 22,
    height: 13,
    font_size: 9,
    font_weight: 'normal',
    alignment: 'center',
    field_type: 'text',
    required: true,
    auto_resize: false,
    sort_order: 33,
    group: 'data',
    default_value: String(new Date().getFullYear()).slice(-2),
    test_value: '26',
  },
];

// 2. CARTA DE CANCELAMENTO
export const FIELDS_CARTA_CANCELAMENTO: TemplateField[] = [
  {
    id: 'f_canc_cliente_nome',
    template_id: 'template_carta_cancelamento',
    field_key: 'cliente_nome',
    label: 'Nome do Cliente',
    description: 'Nome completo do titular solicitante',
    page: 1,
    x: 98,
    y: 183,
    width: 228,
    height: 14,
    font_size: 9.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 1,
    group: 'declarante',
    test_value: 'Mariana Duarte Souza',
  },
  {
    id: 'f_canc_cliente_cpf_cnpj',
    template_id: 'template_carta_cancelamento',
    field_key: 'cliente_cpf_cnpj',
    label: 'CPF / CNPJ',
    description: 'Documento do titular solicitante',
    page: 1,
    x: 138,
    y: 203,
    width: 148,
    height: 14,
    font_size: 9.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'cpf',
    required: true,
    mask: '000.000.000-00',
    auto_resize: true,
    sort_order: 2,
    group: 'declarante',
    test_value: '234.567.890-12',
  },
  {
    id: 'f_canc_valor_numerico',
    template_id: 'template_carta_cancelamento',
    field_key: 'valor_numerico',
    label: 'Valor Pago (R$)',
    description: 'Valor numérico do cancelamento',
    page: 1,
    x: 322,
    y: 223,
    width: 66,
    height: 14,
    font_size: 9.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'currency',
    required: true,
    auto_resize: true,
    sort_order: 3,
    group: 'outros',
    test_value: '9.000,00',
  },
  {
    id: 'f_canc_valor_extenso',
    template_id: 'template_carta_cancelamento',
    field_key: 'valor_extenso',
    label: 'Valor por Extenso',
    page: 1,
    x: 398,
    y: 223,
    width: 108,
    height: 14,
    font_size: 9.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 4,
    group: 'outros',
    test_value: 'nove mil reais',
  },
  {
    id: 'f_canc_concessionaria_nome',
    template_id: 'template_carta_cancelamento',
    field_key: 'concessionaria_nome',
    label: 'Concessionária / Razão Social',
    page: 1,
    x: 160,
    y: 243,
    width: 348,
    height: 14,
    font_size: 9,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 5,
    group: 'comprador',
    default_value: 'CMD GW COMERCIO DE VEICULOS AUTOMOTORES',
    test_value: 'CMD GW COMERCIO DE VEICULOS AUTOMOTORES',
  },
  {
    id: 'f_canc_forma_pagamento',
    template_id: 'template_carta_cancelamento',
    field_key: 'forma_pagamento',
    label: 'Forma de Pagamento Original',
    description: 'Ex: cartão de crédito, PIX, transferência',
    page: 1,
    x: 308,
    y: 283,
    width: 198,
    height: 14,
    font_size: 9.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 6,
    group: 'outros',
    default_value: 'cartão de crédito',
    test_value: 'cartão de crédito',
  },
  {
    id: 'f_canc_data_dia',
    template_id: 'template_carta_cancelamento',
    field_key: 'data_dia',
    label: 'Dia',
    page: 1,
    x: 135,
    y: 383,
    width: 40,
    height: 14,
    font_size: 9.5,
    font_weight: 'normal',
    alignment: 'center',
    field_type: 'number',
    required: true,
    sort_order: 7,
    group: 'data',
    default_value: String(new Date().getDate()).padStart(2, '0'),
    test_value: '19',
  },
  {
    id: 'f_canc_data_mes',
    template_id: 'template_carta_cancelamento',
    field_key: 'data_mes',
    label: 'Mês',
    page: 1,
    x: 188,
    y: 383,
    width: 47,
    height: 14,
    font_size: 9.5,
    font_weight: 'normal',
    alignment: 'center',
    field_type: 'text',
    required: true,
    sort_order: 8,
    group: 'data',
    default_value: String(new Date().getMonth() + 1).padStart(2, '0'),
    test_value: '08',
  },
  {
    id: 'f_canc_data_ano',
    template_id: 'template_carta_cancelamento',
    field_key: 'data_ano',
    label: 'Ano',
    page: 1,
    x: 248,
    y: 383,
    width: 57,
    height: 14,
    font_size: 9.5,
    font_weight: 'normal',
    alignment: 'center',
    field_type: 'year',
    required: true,
    sort_order: 9,
    group: 'data',
    default_value: String(new Date().getFullYear()),
    test_value: '2026',
  },
];

// 3. DECLARAÇÃO DE DAÇÃO EM PAGAMENTO DE VEÍCULO
export const FIELDS_DACAO_PAGAMENTO: TemplateField[] = [
  {
    id: 'f_dac_proprietario_nome',
    template_id: 'template_dacao_pagamento',
    field_key: 'proprietario_nome',
    label: 'Nome do Proprietário',
    page: 1,
    x: 104,
    y: 77,
    width: 426,
    height: 14,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 1,
    group: 'proprietario',
    test_value: 'Carlos Alberto Ferreira',
  },
  {
    id: 'f_dac_proprietario_rg',
    template_id: 'template_dacao_pagamento',
    field_key: 'proprietario_rg',
    label: 'RG do Proprietário',
    page: 1,
    x: 172,
    y: 99,
    width: 132,
    height: 14,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'rg',
    required: true,
    auto_resize: true,
    sort_order: 2,
    group: 'proprietario',
    test_value: '12.345.678',
  },
  {
    id: 'f_dac_proprietario_cpf',
    template_id: 'template_dacao_pagamento',
    field_key: 'proprietario_cpf',
    label: 'CPF do Proprietário',
    page: 1,
    x: 375,
    y: 99,
    width: 155,
    height: 14,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'cpf',
    required: true,
    mask: '000.000.000-00',
    auto_resize: true,
    sort_order: 3,
    group: 'proprietario',
    test_value: '123.456.789-00',
  },
  {
    id: 'f_dac_proprietario_estado_civil',
    template_id: 'template_dacao_pagamento',
    field_key: 'proprietario_estado_civil',
    label: 'Estado Civil',
    page: 1,
    x: 142,
    y: 121,
    width: 162,
    height: 14,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 4,
    group: 'proprietario',
    test_value: 'Casado(a)',
  },
  {
    id: 'f_dac_proprietario_profissao',
    template_id: 'template_dacao_pagamento',
    field_key: 'proprietario_profissao',
    label: 'Profissão',
    page: 1,
    x: 362,
    y: 121,
    width: 168,
    height: 14,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 5,
    group: 'proprietario',
    test_value: 'Engenheiro Civil',
  },
  // Veículo Usado
  {
    id: 'f_dac_usado_placa',
    template_id: 'template_dacao_pagamento',
    field_key: 'usado_placa',
    label: 'Placa (Usado)',
    page: 1,
    x: 118,
    y: 161,
    width: 72,
    height: 14,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'plate',
    required: true,
    auto_resize: true,
    sort_order: 6,
    group: 'veiculo',
    test_value: 'ABC1D23',
  },
  {
    id: 'f_dac_usado_ano_fabricacao',
    template_id: 'template_dacao_pagamento',
    field_key: 'usado_ano_fabricacao',
    label: 'Ano Fabricação (Usado)',
    page: 1,
    x: 272,
    y: 161,
    width: 34,
    height: 14,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'year',
    required: true,
    auto_resize: true,
    sort_order: 7,
    group: 'veiculo',
    test_value: '2022',
  },
  {
    id: 'f_dac_usado_marca',
    template_id: 'template_dacao_pagamento',
    field_key: 'usado_marca',
    label: 'Marca / Modelo (Usado)',
    page: 1,
    x: 350,
    y: 161,
    width: 180,
    height: 14,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 8,
    group: 'veiculo',
    test_value: 'Toyota Corolla Cross',
  },
  {
    id: 'f_dac_usado_chassi',
    template_id: 'template_dacao_pagamento',
    field_key: 'usado_chassi',
    label: 'Chassi (Usado)',
    page: 1,
    x: 124,
    y: 184,
    width: 406,
    height: 14,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'chassis',
    required: true,
    auto_resize: true,
    sort_order: 9,
    group: 'veiculo',
    test_value: '9BWTESTE123456789',
  },
  // Veículo Adquirido
  {
    id: 'f_dac_adquirido_placa',
    template_id: 'template_dacao_pagamento',
    field_key: 'adquirido_placa',
    label: 'Placa (Adquirido)',
    page: 1,
    x: 118,
    y: 225,
    width: 72,
    height: 14,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'plate',
    required: false,
    auto_resize: true,
    sort_order: 10,
    group: 'veiculo',
    test_value: 'FUE2I35',
  },
  {
    id: 'f_dac_adquirido_ano',
    template_id: 'template_dacao_pagamento',
    field_key: 'adquirido_ano',
    label: 'Ano (Adquirido)',
    page: 1,
    x: 228,
    y: 225,
    width: 78,
    height: 14,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'year',
    required: true,
    auto_resize: true,
    sort_order: 11,
    group: 'veiculo',
    test_value: '2026/2026',
  },
  {
    id: 'f_dac_adquirido_marca_modelo',
    template_id: 'template_dacao_pagamento',
    field_key: 'adquirido_marca_modelo',
    label: 'Marca / Modelo (Adquirido)',
    page: 1,
    x: 388,
    y: 225,
    width: 142,
    height: 14,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 12,
    group: 'veiculo',
    test_value: 'GWM Haval H6 GT',
  },
  {
    id: 'f_dac_adquirido_chassi',
    template_id: 'template_dacao_pagamento',
    field_key: 'adquirido_chassi',
    label: 'Chassi (Adquirido)',
    page: 1,
    x: 124,
    y: 248,
    width: 406,
    height: 14,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'chassis',
    required: true,
    auto_resize: true,
    sort_order: 13,
    group: 'veiculo',
    test_value: 'LGWEEUA56TK606976',
  },
  // Comprador
  {
    id: 'f_dac_comprador_nome',
    template_id: 'template_dacao_pagamento',
    field_key: 'comprador_nome',
    label: 'Comprador (Neste ato adquirido por)',
    page: 1,
    x: 260,
    y: 277,
    width: 270,
    height: 14,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 14,
    group: 'comprador',
    default_value: 'DAHRUJ MOTORS LTDA',
    test_value: 'DAHRUJ MOTORS LTDA',
  },
  // Data
  {
    id: 'f_dac_data_extenso',
    template_id: 'template_dacao_pagamento',
    field_key: 'data_extenso',
    label: 'Data por Extenso (Campinas)',
    page: 1,
    x: 368,
    y: 578,
    width: 162,
    height: 14,
    font_size: 8,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 15,
    group: 'data',
    default_value: `${new Date().getDate()} de ${[
      'Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho',
      'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'
    ][new Date().getMonth()]} de ${new Date().getFullYear()}`,
    test_value: '19 de Agosto de 2026',
  },
];

// 4. DECLARAÇÃO DE ISENÇÃO DE NF / ICMS
export const FIELDS_ISENCAO_NF: TemplateField[] = [
  {
    id: 'f_ise_empresa_nome',
    template_id: 'template_isencao_nf_servicos',
    field_key: 'empresa_nome',
    label: 'Nome da Empresa',
    page: 1,
    x: 138,
    y: 134,
    width: 165,
    height: 14,
    font_size: 9.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 1,
    group: 'comprador',
    test_value: 'PRESTADORA DE SERVICOS LTDA',
  },
  {
    id: 'f_ise_empresa_cnpj',
    template_id: 'template_isencao_nf_servicos',
    field_key: 'empresa_cnpj',
    label: 'CNPJ da Empresa',
    page: 1,
    x: 350,
    y: 134,
    width: 142,
    height: 14,
    font_size: 9.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'cnpj',
    required: true,
    mask: '00.000.000/0000-00',
    auto_resize: true,
    sort_order: 2,
    group: 'comprador',
    test_value: '12.345.678/0001-90',
  },
  {
    id: 'f_ise_veiculo_modelo',
    template_id: 'template_isencao_nf_servicos',
    field_key: 'veiculo_modelo',
    label: 'Veículo (Marca/Modelo/Versão)',
    page: 1,
    x: 135,
    y: 334,
    width: 375,
    height: 14,
    font_size: 9.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 3,
    group: 'veiculo',
    test_value: 'GWM HAVAL H6 PHEV 19',
  },
  {
    id: 'f_ise_veiculo_ano',
    template_id: 'template_isencao_nf_servicos',
    field_key: 'veiculo_ano',
    label: 'Ano Fabricação/Modelo',
    page: 1,
    x: 115,
    y: 369,
    width: 395,
    height: 14,
    font_size: 9.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 4,
    group: 'veiculo',
    test_value: '2025/2026',
  },
  {
    id: 'f_ise_veiculo_cor',
    template_id: 'template_isencao_nf_servicos',
    field_key: 'veiculo_cor',
    label: 'Cor do Veículo',
    page: 1,
    x: 110,
    y: 404,
    width: 400,
    height: 14,
    font_size: 9.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 5,
    group: 'veiculo',
    test_value: 'Cinza Diamante',
  },
  {
    id: 'f_ise_veiculo_renavam',
    template_id: 'template_isencao_nf_servicos',
    field_key: 'veiculo_renavam',
    label: 'RENAVAM',
    page: 1,
    x: 138,
    y: 439,
    width: 372,
    height: 14,
    font_size: 9.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 6,
    group: 'veiculo',
    test_value: '01234567890',
  },
  {
    id: 'f_ise_veiculo_chassi',
    template_id: 'template_isencao_nf_servicos',
    field_key: 'veiculo_chassi',
    label: 'Chassi do Veículo',
    page: 1,
    x: 125,
    y: 474,
    width: 385,
    height: 14,
    font_size: 9.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'chassis',
    required: true,
    auto_resize: true,
    sort_order: 7,
    group: 'veiculo',
    test_value: 'LGWEEUA56TK606976',
  },
  {
    id: 'f_ise_cidade_data',
    template_id: 'template_isencao_nf_servicos',
    field_key: 'cidade_data',
    label: 'Cidade e Data',
    page: 1,
    x: 360,
    y: 642,
    width: 155,
    height: 14,
    font_size: 9,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 8,
    group: 'data',
    default_value: `São Paulo, ${new Date().getDate()} de ${[
      'Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho',
      'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'
    ][new Date().getMonth()]} de ${new Date().getFullYear()}`,
    test_value: 'São Paulo, 19 de Agosto de 2026',
  },
];

// 5. TERMO DE COMPRA DO VEÍCULO USADO (GWM)
export const FIELDS_TERMO_COMPRA_USADO_GWM: TemplateField[] = [
  {
    id: 'f_gwm_pedido_rto',
    template_id: 'template_termo_compra_usado_gwm',
    field_key: 'pedido_rto',
    label: 'Pedido RTO',
    page: 1,
    x: 142,
    y: 128,
    width: 190,
    height: 14,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 1,
    group: 'outros',
    test_value: 'RTO-2026-9874',
  },
  {
    id: 'f_gwm_cliente_nome',
    template_id: 'template_termo_compra_usado_gwm',
    field_key: 'cliente_nome',
    label: 'Nome do Cliente',
    page: 1,
    x: 130,
    y: 156,
    width: 298,
    height: 14,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 2,
    group: 'declarante',
    test_value: 'Marcos Vinicius Santos',
  },
  {
    id: 'f_gwm_cliente_cpf',
    template_id: 'template_termo_compra_usado_gwm',
    field_key: 'cliente_cpf',
    label: 'CPF do Cliente',
    page: 1,
    x: 72,
    y: 184,
    width: 136,
    height: 14,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'cpf',
    required: true,
    mask: '000.000.000-00',
    auto_resize: true,
    sort_order: 3,
    group: 'declarante',
    test_value: '345.678.901-23',
  },
  {
    id: 'f_gwm_valor_venda',
    template_id: 'template_termo_compra_usado_gwm',
    field_key: 'valor_venda',
    label: 'Valor da Venda + Extenso',
    page: 1,
    x: 90,
    y: 292,
    width: 248,
    height: 14,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 4,
    group: 'outros',
    test_value: '85.000,00 (oitenta e cinco mil reais)',
  },
  {
    id: 'f_gwm_concessionaria_nome',
    template_id: 'template_termo_compra_usado_gwm',
    field_key: 'concessionaria_nome',
    label: 'Concessionária Compradora',
    page: 1,
    x: 144,
    y: 318,
    width: 192,
    height: 14,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 5,
    group: 'comprador',
    default_value: 'GWM DAHRUJ CAMPINAS',
    test_value: 'GWM DAHRUJ CAMPINAS',
  },
  {
    id: 'f_gwm_veiculo_marca',
    template_id: 'template_termo_compra_usado_gwm',
    field_key: 'veiculo_marca',
    label: 'Marca (Seminovo)',
    page: 1,
    x: 106,
    y: 353,
    width: 64,
    height: 14,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 6,
    group: 'veiculo',
    test_value: 'Jeep',
  },
  {
    id: 'f_gwm_veiculo_modelo',
    template_id: 'template_termo_compra_usado_gwm',
    field_key: 'veiculo_modelo',
    label: 'Modelo (Seminovo)',
    page: 1,
    x: 232,
    y: 353,
    width: 62,
    height: 14,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 7,
    group: 'veiculo',
    test_value: 'Compass',
  },
  {
    id: 'f_gwm_veiculo_versao',
    template_id: 'template_termo_compra_usado_gwm',
    field_key: 'veiculo_versao',
    label: 'Versão (Seminovo)',
    page: 1,
    x: 352,
    y: 353,
    width: 62,
    height: 14,
    font_size: 8,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 8,
    group: 'veiculo',
    test_value: 'Longitude 1.3',
  },
  {
    id: 'f_gwm_veiculo_ano_fab',
    template_id: 'template_termo_compra_usado_gwm',
    field_key: 'veiculo_ano_fab',
    label: 'Ano Fab.',
    page: 1,
    x: 184,
    y: 400,
    width: 32,
    height: 14,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'center',
    field_type: 'year',
    required: true,
    sort_order: 9,
    group: 'veiculo',
    test_value: '2023',
  },
  {
    id: 'f_gwm_veiculo_ano_mod',
    template_id: 'template_termo_compra_usado_gwm',
    field_key: 'veiculo_ano_mod',
    label: 'Ano Mod.',
    page: 1,
    x: 234,
    y: 400,
    width: 32,
    height: 14,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'center',
    field_type: 'year',
    required: true,
    sort_order: 10,
    group: 'veiculo',
    test_value: '2024',
  },
  {
    id: 'f_gwm_veiculo_placa',
    template_id: 'template_termo_compra_usado_gwm',
    field_key: 'veiculo_placa',
    label: 'Placa (Seminovo)',
    page: 1,
    x: 312,
    y: 400,
    width: 112,
    height: 14,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'plate',
    required: true,
    auto_resize: true,
    sort_order: 11,
    group: 'veiculo',
    test_value: 'BRA2E19',
  },
  {
    id: 'f_gwm_veiculo_novo_modelo',
    template_id: 'template_termo_compra_usado_gwm',
    field_key: 'veiculo_novo_modelo',
    label: 'Modelo GWM Novo Adquirido',
    page: 1,
    x: 226,
    y: 462,
    width: 64,
    height: 14,
    font_size: 8.5,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 12,
    group: 'veiculo',
    test_value: 'ORA 03 GT',
  },
  {
    id: 'f_gwm_data_dia',
    template_id: 'template_termo_compra_usado_gwm',
    field_key: 'data_dia',
    label: 'Dia',
    page: 1,
    x: 100,
    y: 508,
    width: 38,
    height: 14,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'center',
    field_type: 'number',
    required: true,
    sort_order: 13,
    group: 'data',
    default_value: String(new Date().getDate()).padStart(2, '0'),
    test_value: '19',
  },
  {
    id: 'f_gwm_data_mes',
    template_id: 'template_termo_compra_usado_gwm',
    field_key: 'data_mes',
    label: 'Mês',
    page: 1,
    x: 154,
    y: 508,
    width: 44,
    height: 14,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'center',
    field_type: 'text',
    required: true,
    sort_order: 14,
    group: 'data',
    default_value: String(new Date().getMonth() + 1).padStart(2, '0'),
    test_value: '08',
  },
  {
    id: 'f_gwm_data_ano',
    template_id: 'template_termo_compra_usado_gwm',
    field_key: 'data_ano',
    label: 'Ano',
    page: 1,
    x: 214,
    y: 508,
    width: 48,
    height: 14,
    font_size: 8.5,
    font_weight: 'normal',
    alignment: 'center',
    field_type: 'year',
    required: true,
    sort_order: 15,
    group: 'data',
    default_value: String(new Date().getFullYear()),
    test_value: '2026',
  },
  {
    id: 'f_gwm_cliente_nome_ass',
    template_id: 'template_termo_compra_usado_gwm',
    field_key: 'cliente_nome_ass',
    label: 'Nome (Assinatura Cliente)',
    page: 1,
    x: 108,
    y: 606,
    width: 144,
    height: 13,
    font_size: 8,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: false,
    auto_resize: true,
    sort_order: 16,
    group: 'comunicacoes',
    test_value: 'Marcos Vinicius Santos',
  },
  {
    id: 'f_gwm_cliente_fone',
    template_id: 'template_termo_compra_usado_gwm',
    field_key: 'cliente_fone',
    label: 'Fone Cliente',
    page: 1,
    x: 108,
    y: 624,
    width: 144,
    height: 13,
    font_size: 8,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'phone',
    required: false,
    auto_resize: true,
    sort_order: 17,
    group: 'comunicacoes',
    test_value: '(19) 99123-4567',
  },
  {
    id: 'f_gwm_cliente_email',
    template_id: 'template_termo_compra_usado_gwm',
    field_key: 'cliente_email',
    label: 'E-mail Cliente',
    page: 1,
    x: 112,
    y: 642,
    width: 140,
    height: 13,
    font_size: 8,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'email',
    required: false,
    auto_resize: true,
    sort_order: 18,
    group: 'comunicacoes',
    test_value: 'marcos.santos@email.com',
  },
  {
    id: 'f_gwm_concess_nome',
    template_id: 'template_termo_compra_usado_gwm',
    field_key: 'concess_nome',
    label: 'Nome (Assinatura Concessionária)',
    page: 1,
    x: 350,
    y: 606,
    width: 114,
    height: 13,
    font_size: 8,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: false,
    auto_resize: true,
    sort_order: 19,
    group: 'comprador',
    default_value: 'Rodrigo Oliveira',
    test_value: 'Rodrigo Oliveira',
  },
  {
    id: 'f_gwm_concess_funcao',
    template_id: 'template_termo_compra_usado_gwm',
    field_key: 'concess_funcao',
    label: 'Função (Concessionária)',
    page: 1,
    x: 358,
    y: 624,
    width: 106,
    height: 13,
    font_size: 8,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: false,
    auto_resize: true,
    sort_order: 20,
    group: 'comprador',
    default_value: 'Gerente Comercial',
    test_value: 'Gerente Comercial',
  },
];

// 6. FORMULÁRIO PARA DEVOLUÇÃO (GWM | DAHRUJ)
export const FIELDS_FORMULARIO_DEVOLUCAO: TemplateField[] = [
  {
    id: 'f_dev_conta_conjunta_sim',
    template_id: 'template_formulario_devolucao',
    field_key: 'conta_conjunta_sim',
    label: 'Conta Conjunta: [X] SIM',
    description: 'Marcar com X se a conta for conjunta',
    page: 1,
    x: 189,
    y: 133,
    width: 12,
    height: 12,
    font_size: 9,
    font_weight: 'bold',
    alignment: 'center',
    field_type: 'checkbox',
    required: false,
    sort_order: 1,
    group: 'outros',
    test_value: '',
  },
  {
    id: 'f_dev_conta_conjunta_nao',
    template_id: 'template_formulario_devolucao',
    field_key: 'conta_conjunta_nao',
    label: 'Conta Conjunta: [X] NÃO',
    description: 'Marcar com X se a conta for individual',
    page: 1,
    x: 276,
    y: 133,
    width: 12,
    height: 12,
    font_size: 9,
    font_weight: 'bold',
    alignment: 'center',
    field_type: 'checkbox',
    required: false,
    sort_order: 2,
    group: 'outros',
    test_value: 'X',
  },
  {
    id: 'f_dev_terceiro_sim',
    template_id: 'template_formulario_devolucao',
    field_key: 'terceiro_sim',
    label: 'Conta Terceiro: [X] SIM',
    description: 'Marcar com X se a conta for de terceiros',
    page: 1,
    x: 189,
    y: 163,
    width: 12,
    height: 12,
    font_size: 9,
    font_weight: 'bold',
    alignment: 'center',
    field_type: 'checkbox',
    required: false,
    sort_order: 3,
    group: 'outros',
    test_value: '',
  },
  {
    id: 'f_dev_terceiro_nao',
    template_id: 'template_formulario_devolucao',
    field_key: 'terceiro_nao',
    label: 'Conta Terceiro: [X] NÃO',
    description: 'Marcar com X se a conta for do próprio titular',
    page: 1,
    x: 276,
    y: 163,
    width: 12,
    height: 12,
    font_size: 9,
    font_weight: 'bold',
    alignment: 'center',
    field_type: 'checkbox',
    required: false,
    sort_order: 4,
    group: 'outros',
    test_value: 'X',
  },
  {
    id: 'f_dev_chave_pix',
    template_id: 'template_formulario_devolucao',
    field_key: 'chave_pix',
    label: 'Chave PIX',
    page: 1,
    x: 142,
    y: 194,
    width: 190,
    height: 14,
    font_size: 9,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 5,
    group: 'declarante',
    test_value: '123.456.789-00',
  },
  {
    id: 'f_dev_titular_nome',
    template_id: 'template_formulario_devolucao',
    field_key: 'titular_nome',
    label: 'Nome do Titular da Conta',
    page: 1,
    x: 132,
    y: 224,
    width: 200,
    height: 14,
    font_size: 9,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 4,
    group: 'declarante',
    test_value: 'Fernanda Lima de Oliveira',
  },
  {
    id: 'f_dev_titular_cpf_cnpj',
    template_id: 'template_formulario_devolucao',
    field_key: 'titular_cpf_cnpj',
    label: 'CPF / CNPJ do Titular',
    page: 1,
    x: 142,
    y: 254,
    width: 190,
    height: 14,
    font_size: 9,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'cpf',
    required: true,
    mask: '000.000.000-00',
    auto_resize: true,
    sort_order: 5,
    group: 'declarante',
    test_value: '123.456.789-00',
  },
  {
    id: 'f_dev_banco_nome',
    template_id: 'template_formulario_devolucao',
    field_key: 'banco_nome',
    label: 'Banco / Instituição',
    page: 1,
    x: 130,
    y: 284,
    width: 202,
    height: 14,
    font_size: 9,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 6,
    group: 'outros',
    test_value: 'Itaú Unibanco (341)',
  },
  {
    id: 'f_dev_agencia_numero',
    template_id: 'template_formulario_devolucao',
    field_key: 'agencia_numero',
    label: 'Agência (com dígito)',
    page: 1,
    x: 138,
    y: 314,
    width: 194,
    height: 14,
    font_size: 9,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 7,
    group: 'outros',
    test_value: '1234',
  },
  {
    id: 'f_dev_conta_poupanca',
    template_id: 'template_formulario_devolucao',
    field_key: 'conta_poupanca',
    label: 'Conta Poupança (se houver)',
    page: 1,
    x: 182,
    y: 344,
    width: 150,
    height: 14,
    font_size: 9,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: false,
    auto_resize: true,
    sort_order: 8,
    group: 'outros',
    test_value: '',
  },
  {
    id: 'f_dev_conta_corrente',
    template_id: 'template_formulario_devolucao',
    field_key: 'conta_corrente',
    label: 'Conta Corrente (com dígito)',
    page: 1,
    x: 182,
    y: 374,
    width: 150,
    height: 14,
    font_size: 9,
    font_weight: 'bold',
    alignment: 'left',
    field_type: 'text',
    required: true,
    auto_resize: true,
    sort_order: 9,
    group: 'outros',
    test_value: '12345-6',
  },
  {
    id: 'f_dev_operacao_cef',
    template_id: 'template_formulario_devolucao',
    field_key: 'operacao_cef',
    label: 'Operação CEF (Ex: 013)',
    page: 1,
    x: 268,
    y: 404,
    width: 70,
    height: 14,
    font_size: 9,
    font_weight: 'normal',
    alignment: 'left',
    field_type: 'text',
    required: false,
    auto_resize: true,
    sort_order: 10,
    group: 'outros',
    test_value: '',
  },
  {
    id: 'f_dev_data_dia',
    template_id: 'template_formulario_devolucao',
    field_key: 'data_dia',
    label: 'Dia',
    page: 1,
    x: 238,
    y: 584,
    width: 35,
    height: 14,
    font_size: 9,
    font_weight: 'normal',
    alignment: 'center',
    field_type: 'number',
    required: true,
    sort_order: 11,
    group: 'data',
    default_value: String(new Date().getDate()).padStart(2, '0'),
    test_value: '19',
  },
  {
    id: 'f_dev_data_mes',
    template_id: 'template_formulario_devolucao',
    field_key: 'data_mes',
    label: 'Mês',
    page: 1,
    x: 290,
    y: 584,
    width: 43,
    height: 14,
    font_size: 9,
    font_weight: 'normal',
    alignment: 'center',
    field_type: 'text',
    required: true,
    sort_order: 12,
    group: 'data',
    default_value: String(new Date().getMonth() + 1).padStart(2, '0'),
    test_value: '08',
  },
  {
    id: 'f_dev_data_ano',
    template_id: 'template_formulario_devolucao',
    field_key: 'data_ano',
    label: 'Ano',
    page: 1,
    x: 350,
    y: 584,
    width: 53,
    height: 14,
    font_size: 9,
    font_weight: 'normal',
    alignment: 'center',
    field_type: 'year',
    required: true,
    sort_order: 13,
    group: 'data',
    default_value: String(new Date().getFullYear()),
    test_value: '2026',
  },
];

// ALL 6 STANDARD BUILT-IN TEMPLATES (Padrão)
export const ALL_BUILT_IN_TEMPLATES: DocumentTemplate[] = [
  {
    id: 'template_termo_responsabilidade',
    name: 'Termo de Responsabilidade',
    description: 'Termo de responsabilidade para transferência de posse e custódia de veículo com dados de declarante, comprador, veículo, proprietário e comunicações.',
    file_hash: 'hash_termo_responsabilidade_v4',
    version: CURRENT_TEMPLATE_VERSION,
    page_count: 1,
    page_width: PAGE_WIDTH,
    page_height: PAGE_HEIGHT,
    status: 'active',
    fields: FIELDS_TERMO_RESPONSABILIDADE,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-08-19T00:00:00.000Z',
    is_built_in: true,
  },
  {
    id: 'template_carta_cancelamento',
    name: 'Carta de Cancelamento (GWM Dahruj)',
    description: 'Solicitação formal de cancelamento e estorno de pagamento à concessionária CMD GW Comércio de Veículos Automotores.',
    file_hash: 'hash_carta_cancelamento_v4',
    version: CURRENT_TEMPLATE_VERSION,
    page_count: 1,
    page_width: PAGE_WIDTH,
    page_height: PAGE_HEIGHT,
    status: 'active',
    fields: FIELDS_CARTA_CANCELAMENTO,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-08-19T00:00:00.000Z',
    is_built_in: true,
  },
  {
    id: 'template_dacao_pagamento',
    name: 'Declaração de Dação em Pagamento',
    description: 'Dação em pagamento de veículo usado na aquisição de novo veículo junto à Dahruj Motors Ltda com termos de responsabilidade e garantia.',
    file_hash: 'hash_dacao_pagamento_v4',
    version: CURRENT_TEMPLATE_VERSION,
    page_count: 1,
    page_width: PAGE_WIDTH,
    page_height: PAGE_HEIGHT,
    status: 'active',
    fields: FIELDS_DACAO_PAGAMENTO,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-08-19T00:00:00.000Z',
    is_built_in: true,
  },
  {
    id: 'template_isencao_nf_servicos',
    name: 'Declaração de Isenção de NF (ICMS)',
    description: 'Declaração de desobrigação de emissão de Nota Fiscal de Venda modelo 1 por atividade exclusiva de prestação de serviços.',
    file_hash: 'hash_isencao_nf_v4',
    version: CURRENT_TEMPLATE_VERSION,
    page_count: 1,
    page_width: PAGE_WIDTH,
    page_height: PAGE_HEIGHT,
    status: 'active',
    fields: FIELDS_ISENCAO_NF,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-08-19T00:00:00.000Z',
    is_built_in: true,
  },
  {
    id: 'template_termo_compra_usado_gwm',
    name: 'Termo de Compra de Usado (GWM)',
    description: 'Termo de compra e declaração de venda de veículo seminovo como parte de pagamento na aquisição de veículo novo GWM.',
    file_hash: 'hash_termo_compra_gwm_v4',
    version: CURRENT_TEMPLATE_VERSION,
    page_count: 1,
    page_width: PAGE_WIDTH,
    page_height: PAGE_HEIGHT,
    status: 'active',
    fields: FIELDS_TERMO_COMPRA_USADO_GWM,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-08-19T00:00:00.000Z',
    is_built_in: true,
  },
  {
    id: 'template_formulario_devolucao',
    name: 'Formulário para Devolução (PIX/TED)',
    description: 'Formulário oficial para solicitação de devolução de valores via PIX, TED ou Conta Bancária com termos e dados de titular.',
    file_hash: 'hash_formulario_devolucao_v4',
    version: CURRENT_TEMPLATE_VERSION,
    page_count: 1,
    page_width: PAGE_WIDTH,
    page_height: PAGE_HEIGHT,
    status: 'active',
    fields: FIELDS_FORMULARIO_DEVOLUCAO,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-08-19T00:00:00.000Z',
    is_built_in: true,
  },
];

export const BUILT_IN_TEMPLATE_RESPONSABILIDADE = ALL_BUILT_IN_TEMPLATES[0];

export function createDefaultFieldsForTemplate(templateId: string): TemplateField[] {
  const match = ALL_BUILT_IN_TEMPLATES.find((t) => t.id === templateId);
  const baseFields = match ? match.fields : FIELDS_TERMO_RESPONSABILIDADE;
  return baseFields.map((f, idx) => ({
    ...f,
    id: `f_${templateId}_${idx + 1}_${Date.now()}`,
    template_id: templateId,
  }));
}

// Master PDF buffer in-memory cache
const cachedMasterPdfs: Record<string, Uint8Array> = {};

export async function getMasterPdfBytes(template: DocumentTemplate): Promise<Uint8Array> {
  const templateId = template.id;

  // If template has an embedded original PDF file (from upload), always use it directly
  if (template.file_url && template.file_url.startsWith('data:application/pdf;base64,')) {
    try {
      const base64Data = template.file_url.split(',')[1];
      const binaryString = atob(base64Data);
      const len = binaryString.length;
      const b = new Uint8Array(len);
      for (let i = 0; i < len; i++) {
        b[i] = binaryString.charCodeAt(i);
      }
      return b;
    } catch (e) {
      console.warn('Error parsing base64 PDF from template file_url:', e);
    }
  }

  if (cachedMasterPdfs[templateId]) {
    return cachedMasterPdfs[templateId];
  }

  let bytes: Uint8Array;

  switch (templateId) {
    case 'template_termo_responsabilidade':
      bytes = await generateMasterResponsabilidadePdf();
      break;
    case 'template_carta_cancelamento':
      bytes = await generateMasterCartaCancelamentoPdf();
      break;
    case 'template_dacao_pagamento':
      bytes = await generateMasterDacaoPagamentoPdf();
      break;
    case 'template_isencao_nf_servicos':
      bytes = await generateMasterIsencaoNfPdf();
      break;
    case 'template_termo_compra_usado_gwm':
      bytes = await generateMasterTermoCompraUsadoGwmPdf();
      break;
    case 'template_formulario_devolucao':
      bytes = await generateMasterFormularioDevolucaoPdf();
      break;
    default:
      bytes = await generateMasterResponsabilidadePdf();
      break;
  }

  cachedMasterPdfs[templateId] = bytes;
  return bytes;
}

// Storage Utilities
export function loadAllTemplates(): DocumentTemplate[] {
  try {
    const raw = localStorage.getItem(TEMPLATES_STORAGE_KEY);
    if (!raw) {
      localStorage.setItem(TEMPLATES_STORAGE_KEY, JSON.stringify(ALL_BUILT_IN_TEMPLATES));
      return ALL_BUILT_IN_TEMPLATES;
    }
    const parsed: DocumentTemplate[] = JSON.parse(raw);
    let changed = false;

    // Ensure all built-in templates exist and are updated
    for (const builtIn of ALL_BUILT_IN_TEMPLATES) {
      const idx = parsed.findIndex((t) => t.id === builtIn.id);
      if (idx >= 0) {
        if (parsed[idx].version !== CURRENT_TEMPLATE_VERSION || (parsed[idx].fields || []).length !== builtIn.fields.length) {
          parsed[idx] = builtIn;
          changed = true;
        }
      } else {
        parsed.push(builtIn);
        changed = true;
      }
    }

    if (changed) {
      localStorage.setItem(TEMPLATES_STORAGE_KEY, JSON.stringify(parsed));
    }

    return parsed;
  } catch {
    return ALL_BUILT_IN_TEMPLATES;
  }
}

export function saveTemplate(template: DocumentTemplate): void {
  const all = loadAllTemplates();
  const index = all.findIndex((t) => t.id === template.id);
  if (index >= 0) {
    all[index] = { ...template, updated_at: new Date().toISOString() };
  } else {
    all.push({
      ...template,
      created_at: template.created_at || new Date().toISOString(),
      updated_at: new Date().toISOString(),
    });
  }
  localStorage.setItem(TEMPLATES_STORAGE_KEY, JSON.stringify(all));
}

export function deleteTemplate(templateId: string): void {
  const all = loadAllTemplates().filter((t) => t.id !== templateId && !t.is_built_in);
  localStorage.setItem(TEMPLATES_STORAGE_KEY, JSON.stringify(all));
}

export function loadDocumentHistory(): GeneratedDocument[] {
  try {
    const raw = localStorage.getItem(HISTORY_STORAGE_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
}

export function saveDocumentToHistory(doc: GeneratedDocument): void {
  const history = loadDocumentHistory();
  history.unshift(doc);
  if (history.length > 50) history.pop();
  localStorage.setItem(HISTORY_STORAGE_KEY, JSON.stringify(history));
}

export function deleteDocumentFromHistory(docId: string): void {
  const history = loadDocumentHistory().filter((d) => d.id !== docId);
  localStorage.setItem(HISTORY_STORAGE_KEY, JSON.stringify(history));
}

export function clearAllDocumentHistory(): void {
  localStorage.removeItem(HISTORY_STORAGE_KEY);
}
